### ISSUE TITLE
Slideshow transitions

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#16]
Make the image transitions happen over time to give it a nicer feel.

**Comment by N-Yuki** [comment]
Possibly slide-in from the side.

**Comment by EaTea** [comment]
At the moment I don't wanna touch the code for this but I think this might be helpful:

http://stackoverflow.com/questions/5859409/how-to-slide-images-in-from-the-side-using-javascript

**Comment by N-Yuki** [comment]
Implemented slide-in: gh-16/testing
Current limitation is that it only has 2 images at any one time. A possible solution to this would be to continuously stack them on top of each other but this has the issue of possible overflow if left for long enough, so it'll need periodic resetting.
