### ISSUE TITLE
README documentation

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#17]
Quote of point 7 for Stage I requirements (also on the wiki):

> Appropriate use of the following techniques and provide a README file (can be in plain text) to document the rationale and how you used them. This README file should also help the project marker to locate which pages contain the required technique.
> - Form Controls
> - CSS
> - Client-side Programming: Javascript - Basic form validation
> - Demonstrating the use of DHTML (A combination of CSS, JavaScript, DOM and Event Models)

**Comment by N-Yuki** [comment]
This will probably be one of the last ones to close before Stage 1 due date, so if you have anything to add then just say so here and we'll add it all to the file at the end.

**Comment by EaTea** [comment]
Form controls: Home Page.
CSS: Every page.
Validation: Home Page.
DHTML: Home Page.

All the eggs are in one basket. Slightly worrying.

We could do a bit of code reuse and put the slideshow on the features page.
But it isn't really necessary, and I think we've shown off most of the
required features.

I'll open up an issue sometime today and write it up in the README myself.
Please write down any specific issues that you've noted that I should cover,
and rationale regarding the pages that you'd like to explicitly mention in
the README.

On 22 September 2011 02:25, S0uten <
reply@reply.github.com>wrote:

> Quote of point 7 for Stage I requirements (also on the wiki):
> 
> > Appropriate use of the following techniques and provide a README file
> > (can be in plain text) to document the rationale and how you used them. This
> > README file should also help the project marker to locate which pages
> > contain the required technique.
> > - Form Controls
> > - CSS
> > - Client-side Programming: Javascript - Basic form validation
> > - Demonstrating the use of DHTML (A combination of CSS, JavaScript, DOM
> >   and Event Models)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/EaTea/CITS4230-Project-Group-7/issues/17

## 

Edwin Tay
