### ISSUE TITLE
Header and Footer Templates

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#2]
Header should include:
- Site Logo (or slogan, motto to help people remembering your site)
- Navigation bar(s)
- Login form (for when not logged in)

Footer should include:
- Disclaimer, Copyright, Last modified date, and contact information (e.g. web master's name and email address provided in a way to avoid collection from spam software)

**Comment by N-Yuki** [comment]
"Last modified date" doesn't seem very useful, but should we have it? I guess we could have it as meta data or something. Although, we'll probably need PHP or something to check the age of content.php

Also, I'm not sure what to add for "Disclaimer". Should that really be a template thing?

If these are not needed, then I'll probably close this once I add a logo (need an image...) and/or slogan.

**Comment by EaTea** [comment]
"Last modified date" seems like a bit of a burden to implement fully and
does not add value to our project. Removing it is acceptable in my opinion.

Disclaimer can be removed, as far as I'm concerned. It is covered within the
privacy policy.

On 22 September 2011 02:22, S0uten <
reply@reply.github.com>wrote:

> "Last modified date" doesn't seem very useful, but should we have it? I
> guess we could have it as meta data or something. Although, we'll probably
> need PHP or something to check the age of content.php
> 
> Also, I'm not sure what to add for "Disclaimer". Should that really be a
> template thing?
> 
> If these are not needed, then I'll probably close this once I add a logo
> (need an image...) and/or slogan.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/EaTea/CITS4230-Project-Group-7/issues/2#issuecomment-2159167

## 

Edwin Tay

**Comment by EaTea** [comment]
Minor issue I noticed --- the breadcrumbs are a little odd. If possible, it'd be nice to change the student.csse.... to just XYZ. I've just gotten back and I'll be away from the computer for a bit but I'll change it tonight if it's not done by someone else.
