### ISSUE TITLE
Database Creation in SQLite

### ISSUE THREAD

**Issue by EaTea** [EaTea/CITS4230-Project-Group-7#23]
We need a Database in SQLite and the scripts to be able to create one available. It would be good if we could update the wiki to reflect the changes and how to use the SQL scripts with SQLite.

**Comment by sontobgay** [comment]
MySQL database created on cits4230g mysql server. Following database credentials have to be specified from rails config file to connect to the database:

Still some problem with SQlite. Not able to create a database on [/home/cits4230/cits4230g/todo/db/] directory. May be some file permission problem. I can do it on my local machine but not on cits4230g sqlite server. Will try to sort it out soon.

**Comment by EaTea** [comment]
A bit of experimentation on this issue allowed us to create an SQLite Database on the school server. The .sql script appears to work fine. We need some dummy values now in a CSV format for at least the user group of the tables. Sonam, could you give us a dummy file in CSV so we can use them in our databases?

**Comment by EaTea** [comment]
Could we also get the ER diagram committed into a branch called database? I'd like to put it up on the Wiki pages. Thanks sontobgay.

**Comment by sontobgay** [comment]
As per today[06/10/2011] lecture, its seems we have to create a database migration file for the database. So will try creating one tonight and commit to github.

**Comment by EaTea** [comment]
Awesome! Good to here, please let us know how you're going with the
migration and if you run into any difficulties.

On 6 October 2011 13:42, sontobgay <
reply@reply.github.com>wrote:

> As per today[06/10/2011] lecture, its seems we have to create a database
> migration file for the database. So will try creating one tonight and commit
> to github.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/EaTea/CITS4230-Project-Group-7/issues/23#issuecomment-2306715

## 

Edwin Tay

**Comment by EaTea** [comment]
Heya, I just wanted to check how the migration was going? Did you manage to get the migration working, and if so, could you please upload it to the repository? If you're having trouble getting the Rails to run nicely, please let myself or S0uten know. Even if it doesn't work, as long as you're committing it to some safe branch, everything should be okay. Please don't leave us in the dark about what's happening, okay?

**Comment by N-Yuki** [comment]
If it'll help, I just rebased the "db" branch onto the latest master and named it "database". From there, you'll have access to the whole rails thing I setup in master thus you don't need to do stuff out of tree.

**Comment by sontobgay** [comment]
Hey guys, I tried creating the migration file for the tables we already have in your database. The thing with migration is that, it is supposed to be created before we create the actual tables in the backend database. But In case of ours, its the opposite, we create our tables first and now we are trying to create the migration file. Also, please refer, http://guides.rubyonrails.org/migrations.html#active-record-and-referential-integrity. Especially, with regard to foreign key referential integrity, things are not straight forward from migration command. So I am failing to go ahead with the migration. I would have definitely committed something if I was lucky enough to have one migration file created. Definitely don't have the intention to keep you guys in dark...lol.

**Comment by N-Yuki** [comment]
Examples I see on the web have the line:
DROP TABLE IF EXISTS `aaa`;
before creating tables in the SQL script, so do we want this as well?

**Comment by EaTea** [comment]
sontobgay, can you try the migration with the assumption that the tables aren't created yet? Since all your work should already be on the database branch, it won't be an issue if something really weird happens. If foreign key integrity and referential integrity are not being well-encoded through migration at the moment, ignore it for now and just get the database itself up.

I think, based on what I read, we'll have to enforce integrity through our Rails model, which may or may not be more explicit than in SQL. If the migration still isn't working, let me know and I'll try a migration myself.

**Comment by sontobgay** [comment]
I haven't created the migration file (optional as specified in the documentation, especially if you have the backend tables already up. Useful when the DB design changes time and again and thereby used to track the changes). However, docs suggest to create migration schema, which I did using following command. The rake command was ran from /todo/db/ DIRECTORY:
[Project Root Dir]/todo/do> rake db:migrate
--schema.rb generated under [db] dir.

**Comment by EaTea** [comment]
Hi all. The first set of scaffolding is up.

Please rake this database only for testing purposes as I still need to modify the migrations to reflect the foreign key constraints. It is not yet a complete database schema.

Also, you'll notice that due to the restricted types, everything that was previously a VARCHAR is now a string. We will need to enforce the logic of the data size elsewhere, it appears. Sorry about that.

**Comment by N-Yuki** [comment]
This issue itself is not so relevant now with the migration stuff done. The DB should be created now and in master.
