### ISSUE TITLE
Integrate Rails into Git

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#24]
Get rails working, and write scripts to make it testable on the local system.

**Comment by sontobgay** [comment]
If we have finalised the database schemas, should we go with creating[rake] models, controllers and views for the database entities[tables]?

**Comment by N-Yuki** [comment]
I'm assuming the above comment was for GH-23?

**Comment by N-Yuki** [comment]
Rails is now in master and helper scripts have been added.
