### ISSUE TITLE
Form validations and database allocation sizes

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#29]
We need to decide bounds so we don't get inputs larger than the space allocated in the database.
Once we decide the bounds, the form validations should be updated accordingly.
This includes:
- Updating the ECMAScript validation.
- The HTML5 validation currently only checks for non-empty, but it also supports regexp and length constraints, so they should be copied over from the validation script.
- Finally, we want server-side validation as well either through PHP or Ruby on Rails, whichever is better.

Affects: master

**Comment by EaTea** [comment]
With regards to the validation it appears to be half working. I opened an issue on the first bug I found. Will test a little more thoroughly tomorrow morning. Seems to be quite a nice model, if I might say so myself.

Does length validations on the server side like you asked. Need to check why emails are failing, might change it to using the regexp version instead.

On a side note, I redid the entire migration generation because our initial modelling on the ER was buggy and caused some kind of fault within the framework that was too nontrivial to fix to justify me finding out how to do it. Sorry about that. Hence, migration_2 contains the latest migration files. Still working on that branch for now unless you rebase and all that.

**Comment by N-Yuki** [comment]
So just to verify, when someone signs up, should they be directed to a view in the todo rails project?

If that's so, I guess we can set it up to do:
index.php -> todo/\* -auto-redirect-> index.php

**Comment by N-Yuki** [comment]
Also, once the validation stuff has been finalised and the local script validation is synced with it, I can copy them to the HTML5 validation as well if necessary.

**Comment by EaTea** [comment]
Heya, sorry I took so long to respond to this. Yeah, that would be a really good idea actually. Will it be possible to integrate the home page to use the rails validation methods? Doing the task again in PHP/Javascript will be annoying.

I'm adding a gem dependency to apply a model level composite primary key to the validation.

The gem is composite_primary_keys, you can gem it using `gem install composite_primary_keys`. This should be okay, right? I'll detail how to install it into the project directory in a moment.

**Comment by EaTea** [comment]
Getting the dependency set up has not gone well at all. For the last hour I've tried getting it working, and I've really had no luck at all setting up the dependency.

Installing it locally has allowed me to use irb to validate its existence, that is, within irb, require 'rubygems' and require 'composite_primary_keys' works, but this doesn't carry over to the project itself. I can't seem to set environment.rb to correctly find my gems.

Also, doing a local install of the gems hasn't been possible for me. Has anyone else tried this?

**Comment by N-Yuki** [comment]
I don't mind the extra the gems if they won't interfere with other stuff.

Also, YAY, I finally worked out how I can carry over the PHP form inputs into using users/new ,so yeah, doing the validation in Rails will mean the PHP really only has to just do the email == verify-email && password == verify-password then it can pass the form inputs to Rails to verify.

Now, I really need the migration stuff to do this, so I'll really like it if the migration can be merged into master. Is it ready to merge yet? I need to modify the view and controller for user for this to work, so I'll like them to be somewhat stable.

**Comment by EaTea** [comment]
Not ready; the extra dependency issue is limiting how safe the database is
at the moment. Give it one more day, I need to discuss with you guys about
how it's gone with the migration and what it looks like at the moment. Also
fixed another bug in the permissions migration, a little bit annoyed that I
didn't see this one coming...-_-'

On 25 October 2011 02:20, S0uten <
reply@reply.github.com>wrote:

> I don't mind the extra the gems if they won't interfere with other stuff.
> 
> Also, YAY, I finally worked out how I can carry over the PHP form inputs
> into using users/new ,so yeah, doing the validation in Rails will mean the
> PHP really only has to just do the email == verify-email && password ==
> verify-password then it can pass the form inputs to Rails to verify.
> 
> Now, I really need the migration stuff to do this, so I'll really like it
> if the migration can be merged into master. Is it ready to merge yet? I need
> to modify the view and controller for user for this to work, so I'll like
> them to be somewhat stable.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/EaTea/CITS4230-Project-Group-7/issues/29#issuecomment-2507215

## 

Edwin Tay

**Comment by N-Yuki** [comment]
I just noticed that you added the confirmation for the password in the Rails thing. I guess that works as well.

Also, I'm not liking 1b12e351b476497e6dc1080e94d7ce0c965ddbf8 this is stepping outside of migration stuff and I already made a different fix to it outside this branch. If you really need this, then just say you are done with migration then I'll merge the branch.

**Comment by EaTea** [comment]
In my commit, I noted this was a temporary fix. I understand that this isn't a desirable solution and I've enabled it for testing purposes only. Did I bundle it together with multiple files? My bad...

Anyway, I'm not done with the migrations. When it comes to merge, you might have to manually deal with that one unfortunately...sorry about that. I only committed it to have a history of how I was testing.

**Comment by N-Yuki** [comment]
Okay.
Well, I may just need to work off migration_2 to get stuff working for now, then.

Also, is the old migration branch meant to be deleted?

**Comment by EaTea** [comment]
That should be okay to delete. Had been a bit hesitant but it should be okay
now.

On 25 October 2011 02:34, S0uten <
reply@reply.github.com>wrote:

> Okay.
> Well, I may just need to work off migration_2 to get stuff working for now,
> then.
> 
> Also, is the old migration branch meant to be deleted?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/EaTea/CITS4230-Project-Group-7/issues/29#issuecomment-2507389

## 

Edwin Tay

**Comment by N-Yuki** [comment]
Well, I should have tweaked and synced the regexp all up, so they do equivalent stuff even if they are not textually equal.
