### ISSUE TITLE
Send out email reminders

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#31]
Send out an email to all users with a list of all tasks due today.

**Comment by N-Yuki** [comment]
Some useful resources:
- http://www.tutorialspoint.com/ruby-on-rails/rails-send-email.htm
- http://railscasts.com/episodes/61-sending-email

@sontobgay:
I'm going to assign this to you unless there are objections.

**Comment by sontobgay** [comment]
No Objection. I can take up the testing aspects.

**Comment by sontobgay** [comment]
Hi S0uten, so careless of me. As you can see on the github, it seems i have create a new branch named test2 and committed my notification mail to "test2" rather than "tests2". is it possible to merge my committed stuffs in "test2" to "tests2"? If possible do it for me. Sorry for the inconveniences.

**Comment by N-Yuki** [comment]
I put it in an email branch, so it doesn't get confused with the testing.

**Comment by N-Yuki** [comment]
Working now.
