### ISSUE TITLE
Email Validation on User is buggy

### ISSUE THREAD

**Issue by EaTea** [EaTea/CITS4230-Project-Group-7#32]
Problem arises when submitting invalid Email into the email field for User. Causes an exception regarding a local variable.

Affects: migration_2

**Comment by N-Yuki** [comment]
http://cits4230y.csse.uwa.edu.au/sample/

**Comment by EaTea** [comment]
Sorry, can I get some context? I can get around to implementing this a
little later after the other validations are done, but was there something
you wanted me to look at specifically or is this just a general example?

On 25 October 2011 22:48, S0uten <
reply@reply.github.com>wrote:

> http://cits4230y.csse.uwa.edu.au/sample/
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/EaTea/CITS4230-Project-Group-7/issues/32#issuecomment-2518069

## 

Edwin Tay

**Comment by N-Yuki** [comment]
Fixed.
