### ISSUE TITLE
Destroy with :link_to depends on Rails JavaScript

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#33]
Deleting entries from a database using an 'a' link doesn't work since it depends on some rails JavaScript.

But fortunately, this is only for "link_to". If we change it to "button_to", then it works without JavaScript.
One downside is that there is no confirmation dialogue, but I think we can get around that with an alternative method of confirming using CSS. Maybe something like the home page's slideshow tabs - hover over a "Yes" tab to show the delete button.

Or we can just comply and add this JavaScript dependency...

**Comment by N-Yuki** [comment]
EaTea suggests we add the dependency.

**Comment by EaTea** [comment]
I don't think it will be scalable if we have multiple features that may rely on Rails javascript. I would prefer to remove this dependency but I believe we can invest our energies more wisely in areas that aren't related to rewriting what's already provided for us.

I do agree that this goes against having external dependencies but I don't think we have enough time to substitute the Javascript code.

If you feel to the contrary, please post it here, as I might be overestimating the amount of change we need to enact.

**Comment by N-Yuki** [comment]
We don't need to rewrite anything. We just need to use buttons instead of anchors. Unless the UI requires us to use anchors, we should be able to just use buttons instead. I'm sure we can restyle the button if the button appearance is an issue.

Or were you talking about the confirmation thing? Personally, I don't see anything wrong with just copying the styles from the Slideshow to have a tabbed confirmation instead of a pop up dialogue, but I guess this does involve a little extra work

**Comment by N-Yuki** [comment]
Well, I've added the prototype and rails scripts in the config branch, so we can add them in if needed.

**Comment by EaTea** [comment]
I noticed that when using a button_to, confirmations don't appear to work. Contrasting this with links which appear to run them just fine. Is anyone having a similar behavioural problem as me? Or have I made another syntactic error?

**Comment by N-Yuki** [comment]
In rails, confirmations only work with link_to and it depends on JS.
As an alternative, use the CSS popup class to make the verification like I have show as an example for logging out.
