### ISSUE TITLE
Adding attributes to Rails generated tags

### ISSUE THREAD

**Issue by sontobgay** [EaTea/CITS4230-Project-Group-7#37]
Adding "class" and "id" to view files generated by rails scaffold feature don't seem to be straight forward. The current CSS styles applied to view files are still distorted! Can one of you help me. Meanwhile I will still try to resolve the issue.

**Comment by N-Yuki** [comment]
Okay. I think I got a solution to this.

**Comment by N-Yuki** [comment]
I think you can just use :html => { :class => "aaa", :id => "bbb" }

**Comment by sontobgay** [comment]
Thats correct. I found the same.

**Comment by EaTea** [comment]
For the home view, we'll need the styling to get it up to how it looked in the mockup. I think a lot of the elements are ready for styling now and if we could apply something to it to make it resemble the mockup that'd be awesome...^^
