### ISSUE TITLE
SQL Exception.

### ISSUE THREAD

**Issue by sontobgay** [EaTea/CITS4230-Project-Group-7#39]
After pulling the latest commits from master I switched back to branch styles_rails. But then, when I access the systems: http://localhost:3000/users/ I get the following exception:

ActiveRecord::StatementInvalid in UsersController#index

SQLite3::SQLException: no such table: users: SELECT "users".\* FROM "users"

**Comment by N-Yuki** [comment]
Sorry but I can't replicate it, so I don't know what is causing it.
Make sure you have the latest master and run the server from there.

If you are running rails from styles_rails then it may be getting the exceptions due to an already solved issue.

**Comment by EaTea** [comment]
Make sure you rake the database again if you encounter this issue.
