### ISSUE TITLE
Mockups of the logged in page

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#5]
Draw mock-ups of the logged in page.

**Comment by EaTea** [comment]
Estimated time of Arrival: Saturday

On 14 September 2011 21:23, S0uten <
reply@reply.github.com>wrote:

> Draw mock-ups of the logged in page.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/EaTea/CITS4230-Project-Group-7/issues/5

## 

Edwin Tay

**Comment by EaTea** [comment]
sorry Saturday 17 September 2011

On 14 September 2011 22:21, Edwin Tay ed.r.tay@gmail.com wrote:

> Estimated time of Arrival: Saturday
> 
> On 14 September 2011 21:23, S0uten <
> reply@reply.github.com>wrote:
> 
> > Draw mock-ups of the logged in page.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/EaTea/CITS4230-Project-Group-7/issues/5
> 
> ## 
> 
> Edwin Tay

## 

Edwin Tay

**Comment by EaTea** [comment]
I have uploaded a slightly changed mockup to

[20529864/CITS4230_Files/CITS4230Mockups](http://student.csse.uwa.edu.au/~20529864/CITS4230_Files/CITS4230Mockups/LoggedInV1.png)

It just incorporates some very brief ideas I had when I was making use cases. There is a chance that I will be slowly making the mockups more detailed as I find more bits of functionality to incorporate. I still think that a static version should be very simple and not actually have too much functionality at the moment, so don't worry if my changes aren't being implemented.

**Comment by EaTea** [comment]
This should be closed, as there won't be anymore meaningful changes to the mockups within the timeframe left to us. Issue should be reopened iff more detailed mockups are required.
