### ISSUE TITLE
Text for general pages

### ISSUE THREAD

**Issue by N-Yuki** [EaTea/CITS4230-Project-Group-7#7]
Write the body text for the following pages:
- FAQ Page
- Features
- Terms of Usage

**Comment by EaTea** [comment]
Estimated time of arrival: Sunday 18 September 2011

On 14 September 2011 21:28, S0uten <
reply@reply.github.com>wrote:

> Write the body text for the following pages:
> - FAQ Page
> - Features
> - Terms of Usage
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/EaTea/CITS4230-Project-Group-7/issues/7

## 

Edwin Tay

**Comment by EaTea** [comment]
Okay, the body text for the following pages is up:

<ul>
<li>FAQ Page</li>
<li>Features</li>
</ul>


Privacy policy and terms of usage should be coming sometime tonight.

**Comment by EaTea** [comment]
Body text is up for the privacy policy. (commit: 2d6e0104e488331eeb9c840e1c0dfbeee9b5bab9 1 parent 6bcaf185fd)

Issue closed.
